# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

# Spring配置
spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    mapper:
      # 格式化JSON按照字典顺序排序
      sort-properties-alphabetically: true
  config:
    use-legacy-processing: true
  main:
    allow-circular-references: true
  profiles:
    active: dev




knife4j:
  enable: true
  openapi:
    title: MeChat
    description: "`我是小来福`,**你知道吗**
    # aaa"
    email: v2472331253@163.com
    concat: 1111fufu
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    produces:
      - application/json;charset=GBK
    consumes:
      - application/json;charset=GBK
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - xin.ucode

#mybatis-plus:
#  configuration:
#    cache-enabled: false